routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'backend', 'as' => 'backend.'], function () {
    Route::group(['middleware' => ['guest']], function () {
        Route::post('/', 'Auth\LoginController@login')->name('auth');
        Route::get('/', 'Auth\LoginController@loginForm')->name('login');
    });
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/dashboard', 'Backend\Dashboard\DashboardController@index')->name('dashboard');
        Route::resource('/categories', 'Backend\Category\CategoryController');
        Route::resource('/donors', 'Backend\Donor\DonorController');
        Route::resource('/grants', 'Backend\Grant\GrantController');
        Route::resource('/icons', 'Backend\Category\IcoclassController');
        Route::resource('/regions', 'Backend\Region\RegionController');
        Route::get('/communities/send-reg-link', 'Backend\Community\CommunityController@sendRegLink')->name('communities.sendRegLink');
        Route::resource('/communities', 'Backend\Community\CommunityController');
        Route::resource('/users', 'Backend\User\UserController');
        Route::resource('profile', 'Backend\Profile\ProfileController');
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
});

routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/password-reset', 'Frontend\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::group(['as' => 'frontend.'], function () {
    Route::group(['middleware' => ['guest']], function () {
        Route::post('/', 'Frontend\Auth\LoginController@login')->name('auth');
        Route::get('/registration/{hash}', 'Frontend\Auth\RegistrationController@registration')->name('registration');
        Route::post('/setPassword/', 'Frontend\Auth\RegistrationController@setPassword')->name('setPassword');
        Route::get('/login', 'Frontend\Auth\LoginController@loginForm')->name('login');
        Route::get('/logout', 'Frontend\Auth\LoginController@logout')->name('logout');
        Route::get('/recovery', 'Frontend\Auth\RecoveryController@index')->name('recoveryForm');
        Route::post('/recovery', 'Frontend\Auth\RecoveryController@sendResetLinkEmail')->name('sendResetLink');
        Route::post('/reset', 'Frontend\Auth\ResetPasswordController@reset')->name('reset');
    });
    Route::group(['middleware' => ['community']], function () {
        Route::get('/', 'Frontend\Search\SearchController@index')->name('home');
        Route::group(['as' => 'search.'], function () {
            Route::get('/search', 'Frontend\Search\SearchController@index')->name('index');
            Route::get('/search/results', 'Frontend\Search\SearchController@search')->name('search');
        });
        Route::group(['as' => 'grant.'], function () {
            Route::get('grant/{slug}', 'Frontend\Grant\GrantController@index')->name('index');
        });
        Route::group(['as' => 'favourites.', 'prefix' => 'favourites'], function () {
            Route::get('/', 'Frontend\Favourite\FavouriteController@index')->name('index');
            Route::post('/add/{id}', 'Frontend\Favourite\FavouriteController@add')->name('add');
            Route::post('/remove/{id}', 'Frontend\Favourite\FavouriteController@remove')->name('remove');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'web'], function () {
    include 'backend.php';
    include 'frontend.php';
});

app/Models/Grant/Grant.php
<?php

namespace App\Models\Grant;

use App\Helpers\Helpers;
use App\Models\Category\Category;
use App\Models\Community\Community;
use App\Models\Donor\Donor;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Facades\Storage;

class Grant extends Model
{
    protected $fillable = [
        'title',
        'slug',
        'image',
        'description',
        'active',
        'donor_id',
        'cost',
        'deadline',
        'source_link',
        'views'
    ];

    public const GALLERY_PATH = 'public/images/grants/';

    public function donor(): BelongsTo
    {
        return $this->BelongsTo(Donor::class);
    }

    public function categories_grants(): BelongsToMany
    {
        return $this->belongsToMany(Category::class);
    }

    public function communities_grants(): BelongsToMany
    {
        return $this->belongsToMany(Community::class);
    }

    public function getMenuThumbnailAttribute(): ?string
    {
        return Helpers::getImageCache(
            Storage::url(self::GALLERY_PATH . $this->id . "/" . $this->image),
            100,
            100
        );
    }

    public function getThumbnailAttribute(): ?string
    {
        return Helpers::getImageCache(
            Storage::url(self::GALLERY_PATH . $this->id . "/" . $this->image),
            130,
            100
        );
    }

    public function getThumbnailInnerAttribute(): ?string
    {
        return Helpers::getImageCache(
            Storage::url(self::GALLERY_PATH . $this->id . "/" . $this->image),
            460,
            280
        );
    }

    public function getDeadlineDateAttribute()
    {
        return Carbon::parse($this->deadline)->format('d.m.y');
    }
}

app/Http/Controllers/Backend/Profile/ProfileController.php
<?php

namespace App\Http\Controllers\Backend\Profile;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\ProfileRequest;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{


    public function edit($id)
    {
        if($id != auth()->guard()->user()->id){
            return redirect()->back()->with('error', 'forbidden');
        }
        return view('backend.profile.edit', [
            'user'  => User::find($id),
        ]);
    }

    public function update(ProfileRequest $request, $id)
    {
        $user        = User::find($id);
        $user->name  = $request->name;
        $user->email = $request->email;
        if (isset($request->password)) {
            $user->password = Hash::make($request->password);
        }
        $user->update();
        return redirect()->back()->with('success', __('backend.updated'));
    }
}

app/Http/Controllers/Frontend/Favourite/FavouriteController.php
<?php

namespace App\Http\Controllers\Frontend\Favourite;

use App\Helpers\Helpers;
use Illuminate\Http\JsonResponse;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FavouriteController extends Controller
{
    public function index(Request $request)
    {
        $grants = Helpers::getUser()
            ->communities_grants()
            ->with(['donor', 'categories_grants', 'categories_grants.icoclass'])
            ->where('deadline', '>', date('Y-m-d H:i:s'));
        if ($request->has('order')) {
            $grants->orderBy($request->order);
        }
        return view('frontend.profile.favourites.index', [
            'grants' => $grants->get()
        ]);
    }

    public function add(int $id): ?JsonResponse
    {
        Helpers::getUser()->communities_grants()->attach($id);
        return response()->json([
            'data' => view('frontend.parts.buttons.unlike', [
                'grantId' => $id
            ])->render()
        ]);
    }

    public function remove(int $id): ?JsonResponse
    {
        if (Helpers::getUser()->communities_grants()->detach($id)) {
            return response()->json([
                'data' => view('frontend.parts.buttons.like', [
                    'grantId' => $id
                ])->render()
            ]);
        }
        return null;
    }
}

resources/views/frontend/profile/favourites/index.blade.php
@extends('frontend.layouts.app')
@section('title')
    <title>@lang('frontend.my_grants')</title>
@stop
@section('bodyClass') result @stop

<div class="content">
    <div class="flex flex-column">
        <div class="flex flex-space-between flex-middle">
            <div class="flex flex-column">
                <h1>@lang('frontend.my_grants')</h1>
                <div class="my_grant_sort">
                    <a class="active" href="#">@lang('frontend.favourites')</a>
                    <a class="" href="#">@lang('frontend.archive')</a>
                </div>
            </div>

            @include('frontend.parts.forms.order-results')
        </div>

        <div class="grants_content">
            @forelse($grants as $grant)
                <div class="single_grant">
                    <div class="g_img" style="background: url('{{ $grant->thumbnail }}') "></div>
                    <div class="g_info flex flex-column flex-space-between">
                        <div>
                            <a href="{{ route('frontend.grant.index', ['slug' => $grant->slug]) }}">{{ $grant->title }}</a>
                        </div>
                        <div class="flex flex-space-between">
                            <div class="g_category">
                                @foreach($grant->categories_grants as $category)
                                    <span class="{{ $category->icoclass->name }}"></span> {{ $category->title }}
                                @endforeach
                            </div>
                            <div class="g_time"><span class="icon-time"></span> {{ $grant->deadlineDate }}</div>
                        </div>
                    </div>
                </div>
            @empty
                @lang('frontend.not_found')
            @endforelse
        </div>
        <a href="{{ route('frontend.search.index') }}">
            <button><span class="icon-arrow-left"></span>@lang('frontend.to_search')</button>
        </a>
    </div>
</div>