routes/backend.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'backend', 'as' => 'backend.'], function () {
    Route::group(['middleware' => ['guest']], function () {
        Route::post('/', 'Auth\LoginController@login')->name('auth');
        Route::get('/', 'Auth\LoginController@loginForm')->name('login');
    });
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/dashboard', 'Backend\Dashboard\DashboardController@index')->name('dashboard');
        Route::resource('/categories', 'Backend\Category\CategoryController');
        Route::resource('/donors', 'Backend\Donor\DonorController');
        Route::resource('/grants', 'Backend\Grant\GrantController');
        Route::resource('/icons', 'Backend\Category\IcoclassController');
        Route::resource('/regions', 'Backend\Region\RegionController');
        Route::get('/communities/send-reg-link', 'Backend\Community\CommunityController@sendRegLink')->name('communities.sendRegLink');
        Route::resource('/communities', 'Backend\Community\CommunityController');
        Route::resource('/users', 'Backend\User\UserController');
        Route::resource('profile', 'Backend\Profile\ProfileController');
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
});

routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/password-reset', 'Frontend\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::group(['as' => 'frontend.'], function () {
    Route::group(['middleware' => ['guest']], function () {
        Route::post('/', 'Frontend\Auth\LoginController@login')->name('auth');
        Route::get('/registration/{hash}', 'Frontend\Auth\RegistrationController@registration')->name('registration');
        Route::post('/setPassword/', 'Frontend\Auth\RegistrationController@setPassword')->name('setPassword');
        Route::get('/login', 'Frontend\Auth\LoginController@loginForm')->name('login');
        Route::get('/logout', 'Frontend\Auth\LoginController@logout')->name('logout');
        Route::get('/recovery', 'Frontend\Auth\RecoveryController@index')->name('recoveryForm');
        Route::post('/recovery', 'Frontend\Auth\RecoveryController@sendResetLinkEmail')->name('sendResetLink');
        Route::post('/reset', 'Frontend\Auth\ResetPasswordController@reset')->name('reset');
    });
    Route::group(['middleware' => ['community']], function () {
        Route::get('/', 'Frontend\Search\SearchController@index')->name('home');
        Route::group(['as' => 'search.'], function () {
            Route::get('/search', 'Frontend\Search\SearchController@index')->name('index');
            Route::get('/search/results', 'Frontend\Search\SearchController@search')->name('search');
        });
        Route::group(['as' => 'grant.'], function () {
            Route::get('grant/{slug}', 'Frontend\Grant\GrantController@index')->name('index');
        });
        Route::group(['as' => 'favourites.', 'prefix' => 'favourites'], function () {
            Route::get('/', 'Frontend\Favourite\FavouriteController@index')->name('index');
            Route::post('/add/{id}', 'Frontend\Favourite\FavouriteController@add')->name('add');
            Route::post('/remove/{id}', 'Frontend\Favourite\FavouriteController@remove')->name('remove');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'web'], function () {
    include 'backend.php';
    include 'frontend.php';
});

app/Http/Controllers/Backend/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Backend\Category;

use App\Http\Requests\Backend\CategoryRequest;
use App\Models\Category\Category;
use App\Models\Category\Icoclass;
use App\Repositories\Category\CategoryRepository;
use App\Repositories\Category\RegionRepository;
use App\Repositories\Category\DonorRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\View\View;

class CategoryController extends Controller
{
    protected const LIMIT = 50;
    protected $repository;

    public function __construct(Request $request)
    {
        $this->repository = new CategoryRepository($request);
    }

    public function index(Request $request): View
    {
        $categories = Category::query()->when(
            $request->has('search'), function ($query) use ($request) {
            return $query->where('title', 'LIKE', "%" . $request->search . "%");
        });
        return view('backend.categories.index', [
            'categories' => $categories->latest('updated_at')->paginate(self::LIMIT)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(): View
    {
        return view('backend.categories.create', [
            'icoclasses' => Icoclass::all()->pluck('name', 'id')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request): RedirectResponse
    {
        return redirect(
            route('backend.categories.edit', ['category' => $this->repository->store()]))
            ->with('success', __('backend.created'));
    }

    public function edit($id)
    {
        return view('backend.categories.edit', [
            'category' => Category::findOrFail($id),
            'icoclasses' => Icoclass::all()->pluck('name', 'id')
        ]);
    }

    public function update(CategoryRequest $request, $id): RedirectResponse
    {
        return redirect(
            route('backend.categories.edit', ['category' => $this->repository->update($id)]))
            ->with('success', __('backend.updated'));
    }

    public function destroy($id): RedirectResponse
    {
        Category::findOrFail($id)->delete();
        return redirect(
            route('backend.categories.index'))
            ->with('success', __('backend.deleted'));
    }
}

app/Http/Controllers/Backend/Category/IcoclassController.php
<?php

namespace App\Http\Controllers\Backend\Category;

use App\Http\Requests\Backend\IcoclassRequest;
use App\Models\Category\Category;
use App\Models\Category\Icoclass;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\View\View;

class IcoclassController extends Controller
{
    protected const LIMIT = 50;

    public function index(Request $request): View
    {
        $icons = Icoclass::query()->when(
            $request->has('search'), function ($query) use ($request) {
            return $query->where('title', 'LIKE', "%" . $request->search . "%");
        });
        return view('backend.icons.index', [
            'icons' => $icons->latest('updated_at')->paginate(self::LIMIT)
        ]);
    }

    public function create(): View
    {
        return view('backend.icons.create', [
            'icons' => Icoclass::all()->pluck('name', 'id')
        ]);
    }

    public function store(IcoclassRequest $request): RedirectResponse
    {
        return redirect(
            route('backend.icons.edit', ['icoclass' => Icoclass::create($request->all())]))
            ->with('success', __('backend.created'));
    }


    public function edit($id): View
    {
        return view('backend.icons.edit', [
            'icon' => Icoclass::findOrFail($id)
        ]);
    }

    public function update(IcoclassRequest $request, $id): RedirectResponse
    {
        $icon = Icoclass::findOrFail($id);
        $icon->update($request->all());
        return redirect(
            route('backend.icons.edit', ['icoclass' => $icon]))
            ->with('success', __('backend.updated'));
    }

    public function destroy($id): RedirectResponse
    {
        Icoclass::findOrFail($id)->delete();
        return redirect(
            route('backend.icons.index'))
            ->with('success', __('backend.deleted'));
    }
}

app/Http/Controllers/Backend/Community/CommunityController.php
<?php

namespace App\Http\Controllers\Backend\Community;

use App\Http\Requests\Backend\CommunityRequest;
use App\Models\Community\Community;
use App\Models\Region\Region;
use App\Repositories\Community\CommunityRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;

class CommunityController extends Controller
{

    protected $repository;

    public function __construct(Request $request)
    {
        $this->repository = new CommunityRepository($request);
    }

    public function index(): View
    {
        return view('backend.communities.index', [
            'regions' => Region::query()->orderBy('title')->pluck('title', 'id'),
            'communities' => $this->repository->index()
        ]);
    }

    public function create(): View
    {
        return view('backend.communities.create', [
            'regions' => Region::query()->orderBy('title')->pluck('title', 'id')
        ]);
    }

    public function store(CommunityRequest $request): RedirectResponse
    {
        return redirect(
            route('backend.communities.edit', ['community' => $this->repository->store()]))
            ->with('success', __('backend.created'));
    }

    public function edit($id): View
    {
        $community = Community::with(['region'])->findOrFail($id);
        return view('backend.communities.edit', [
            'community' => $community,
            'regions' => Region::query()->orderBy('title')->pluck('title', 'id')
        ]);
    }

    public function update(CommunityRequest $request, $id): RedirectResponse
    {
        return redirect(
            route('backend.communities.edit', ['grant' => $this->repository->update($id)]))
            ->with('success', __('backend.updated'));
    }

    public function destroy($id)
    {
        $community = Community::findOrFail($id);
        Storage::deleteDirectory(Community::GALLERY_PATH . $community->id);
        $community->delete();
        return redirect()
            ->route('backend.communities.index')->with('success', __('backend.deleted'));
    }

    public function sendRegLink(Request $request): RedirectResponse
    {
        $this->repository->sendRegLink();
        return redirect(
            route('backend.communities.index'))
            ->with('success', __('backend.mail_sended'));
    }
}

app/Http/Controllers/Backend/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Backend\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\View\View;

class DashboardController extends Controller
{
    public function index(): View
    {
        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/Donor/DonorController.php
<?php

namespace App\Http\Controllers\Backend\Donor;

use App\Http\Requests\Backend\DonorRequest;
use App\Models\Donor\Donor;
use App\Repositories\Donor\DonorRepository;
use App\Repositories\Grant\GrantRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;

class DonorController extends Controller
{
    protected const LIMIT = 50;
    protected $repository;

    public function __construct(Request $request)
    {
        $this->repository = new DonorRepository($request);
    }

    public function index(Request $request): View
    {
        $donors = Donor::query()->when(
            $request->has('search'), function ($query) use ($request) {
            return $query->where('title', 'LIKE', "%" . $request->search . "%");
        });
        return view('backend.donors.index', [
            'donors' => $donors->latest('updated_at')->paginate(self::LIMIT)
        ]);
    }

    public function create(): View
    {
        return view('backend.donors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(DonorRequest $request): RedirectResponse
    {
        return redirect(
            route('backend.donors.edit', ['donor' => $this->repository->store()]))
            ->with('success', __('backend.created'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id): View
    {
        return view('backend.donors.edit', [
            'donor' => Donor::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(DonorRequest $request, $id): RedirectResponse
    {
        return redirect(
            route('backend.donors.edit', ['donor' => $this->repository->update($id)]))
            ->with('success', __('backend.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $donor = Donor::findOrFail($id);
        Storage::deleteDirectory(Donor::GALLERY_PATH . $donor->id);
        $donor->delete();
        return redirect()
            ->route('backend.donors.index')->with('success', __('backend.deleted'));
    }
}

app/Http/Controllers/Backend/Grant/GrantController.php
<?php

namespace App\Http\Controllers\Backend\Grant;

use App\Http\Requests\Backend\GrantRequest;
use App\Models\Category\Category;
use App\Models\Donor\Donor;
use App\Models\Grant\Grant;
use App\Repositories\Grant\GrantRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;

class GrantController extends Controller
{
    protected $repository;

    public function __construct(Request $request)
    {
        $this->repository = new GrantRepository($request);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request): View
    {
        $basicGrants = $this->repository->index();
        $grants = clone ($basicGrants)->each(function (Grant $grant) {
            $grant->categories_grants = $grant->categories_grants()->pluck('title')->implode(', ');
            return $grant;
        });
        return view('backend.grants.index', [
            'categories' => Category::all()->pluck('title', 'id'),
            'donors' => Donor::all()->pluck('title', 'id'),
            'grants' => $grants,
            'basicGrants' => $basicGrants
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(): View
    {
        return view('backend.grants.create', [
            'categories' => Category::all()->pluck('title', 'id'),
            'donors' => Donor::all()->pluck('title', 'id')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(GrantRequest $request): RedirectResponse
    {
        return redirect(
            route('backend.grants.edit', ['grant' => $this->repository->store()]))
            ->with('success', __('backend.created'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id): View
    {
        $grant = Grant::with(['categories_grants'])->findOrFail($id);
        return view('backend.grants.edit', [
            'grant' => $grant,
            'categories' => Category::all()->pluck('title', 'id'),
            'donors' => Donor::all()->pluck('title', 'id'),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(GrantRequest $request, $id): RedirectResponse
    {
        return redirect(
            route('backend.grants.edit', ['grant' => $this->repository->update($id)]))
            ->with('success', __('backend.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $grant = Grant::findOrFail($id);
        Storage::deleteDirectory(Grant::GALLERY_PATH . $grant->id);
        $grant->delete();
        return redirect()
            ->route('backend.grants.index')->with('success', __('backend.deleted'));
    }
}

resources/views/backend/donors/create.blade.php
@extends('backend.layouts.app')
@section('pagetitle')
    <div class="page-title">
        <div class="title-env">
            <h1 class="title">@lang('backend.add_category')</h1>
        </div>
        <div class="breadcrumb-env">
            <ol class="breadcrumb bc-1">
                <li>
                    <a href="{{ route('backend.dashboard') }}"><i class="fa-home"></i>@lang('backend.home')</a>
                </li>
                <li>
                    <a href="{{ route('backend.donors.index') }}">@lang('backend.donors')</a>
                </li>
                <li class="active">
                    <strong>@lang('backend.add_category')</strong>
                </li>
            </ol>
        </div>
    </div>
@endsection
@section('content')
    {{ Form::open(['url' => route('backend.donors.store'), 'method' => 'POST', 'class' => 'validate', "novalidate" => 'novalidate', 'files' => true]) }}
    @include('backend.donors.fields')
    {{ Form::close() }}
@endsection

resources/views/backend/donors/edit.blade.php
@extends('backend.layouts.app')
@section('pagetitle')
    <div class="page-title">
        <div class="title-env">
            <h1 class="title">@lang('backend.edit_donor')</h1>
        </div>
        <div class="breadcrumb-env">
            <ol class="breadcrumb bc-1">
                <li>
                    <a href="{{ route('backend.dashboard') }}"><i class="fa-home"></i>@lang('backend.home')</a>
                </li>
                <li>
                    <a href="{{ route('backend.categories.index') }}">@lang('backend.donors')</a>
                </li>
                <li class="active">
                    <strong>@lang('backend.edit_donor')</strong>
                </li>
            </ol>
        </div>
    </div>
@endsection
@section('content')
    {!! Form::model($donor, ['url' => route('backend.donors.update',['id'=> $donor->id]), 'novalidate' => 'novalidate', 'method'=>'PUT','autocomplete'=>'off', 'files' => true]) !!}
    {{ Form::hidden('oldImage', $donor->image) }}
    @include('backend.donors.fields')
    {!! Form::close() !!}
    <div class="hidden">
        {!! Form::open(['route' => ['backend.donors.destroy', $donor->id], 'method' => 'delete']) !!}
        {!! Form::submit(__('backend.delete'), ['class' => 'btn btn-danger js-destroy', 'onclick' => "return confirm('" . __('backend.are_you_sure') . "')"]) !!}
        {!! Form::close() !!}
    </div>

@endsection

resources/views/backend/donors/fields.blade.php
<div class="panel panel-headerless">
    <div class="panel-body">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#main" data-toggle="tab">
                    <span class="visible-xs"><i class="fa-user"></i></span>
                    <span class="hidden-xs">@lang('backend.main')</span>
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="main">
                <div class="member-form-add-header">
                    <div class="row">
                        <div class="col-md-10 col-sm-8">
                            <div class="user-img js-parent">
                                <a href="#" class="js-image-link">
                                    <img src="{{ isset($donor) ? $donor->menuThumbnail : Helpers::getImageCache() }}"
                                         class="img-circle"
                                         alt="user-pic"/>
                                </a>
                                <div class="invisible">
                                    {{Form::file('image', ['accept' => 'image/*', 'class' => 'js-thumbnail'])}}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="member-form-inputs js_parent_div" data-csrf="{{ csrf_token() }}">
                    <div class="row form-group">
                        <div class="col-sm-3">
                            {{ Form::label('title', __('backend.title') . ' *', ['class' => 'control-label']) }}
                        </div>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <a href="#"><i class="fa-child"></i></a>
                                </div>
                                {{  Form::text('title', null, ['class' => 'form-control', 'data-validate' => 'required', 'data-message-required' => 'Поле обязательно для заполнения', "placeholder" => __('title')])}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="form-group">
                <a href="{{ route('backend.categories.index') }}" class="btn btn-white"><span
                        class="fa-arrow-left"></span> @lang('backend.back')</a>
                <button type="submit" class="btn btn-success js_form_submit"><span class="fa-save"></span>
                    <b>@lang('backend.save')</b>
                </button>
                @include('backend.parts.button-remove')
            </div>
        </div>
    </div>

resources/views/backend/donors/index.blade.php
@extends('backend.layouts.app')

@section('pagetitle')
    <div class="page-title">
        <div class="title-env">
            <h1 class="title">@lang('backend.donors')</h1>
        </div>
        <div class="breadcrumb-env">
            <a href="{{ route('backend.donors.create') }}" class="btn btn-success"><span class="fa-plus"></span> @lang('backend.add')</a>
        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <div class="tab-content">
                <div class="tab-pane active" id="all">

                    <table class="table table-hover members-table middle-align">
                        <thead>
                        <tr>
                            <th>id</th>
                            <th width="40%">@lang('backend.title')</th>
                            <th width="40%">@lang('backend.image')</th>
                            <th>@lang('backend.action')</th>
                        </tr>
                        <tr>
                            {{ Form::open(['url' => route('backend.donors.index'), 'method' => 'GET']) }}
                            <th class="hidden-xs hidden-sm"></th>
                            <th>{{ Form::text('search', request()->{'search' ?? ''}, ['class' => 'form-control', 'autocomplete' => false, 'placeholder' => __('title')]) }}</th>
                            <th></th>
                            <th>
                                <button type="submit" class="btn btn-sm btn-success">
                                    <i class="fa fa-search"></i>
                                </button>
                            </th>
                            {{ Form::close() }}
                        </tr>
                        </thead>
                        <tbody class="js-sortable" data-url="{{ url('backend/donors/sort/') }}">
                        @forelse($donors as $donor)
                            <tr class="js-sortable-item" data-id="{{ $donor->id }}">
                                <td class="hidden-xs hidden-sm">
                                    <span class="email">{!! $donor->id !!}</span>
                                </td>
                                <td class="hidden-xs hidden-sm">
                                    <span class="email">{!! $donor->title !!}</span>
                                </td>
                                <td>
                                    <img src="{{ $donor->menuThumbnail }}" alt="{{ $donor->title }}">
                                </td>
                                <td>
                                    <a href="{{ route('backend.donors.edit',['grant'=> $donor]) }}" class="btn btn-sm btn-success">
                                        <i class="linecons-pencil"></i>
                                    </a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6"><p class="text-center">@lang('backend.not_found')</p></td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>

                    <div class="row">
                        <div class="col-sm-6">
                        </div>
                        <div class="col-sm-6 text-right text-center-sm">
                            {{ $donors->appends([request()])->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ url('assets/js/inputmask/jquery.inputmask.bundle.js') }}"></script>
@endsection